// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const USE_CASES_TABLE_NAME_ENV_VAR = 'USE_CASES_TABLE_NAME';
export const USE_CASE_CONFIG_TABLE_NAME_ENV_VAR = 'USE_CASE_CONFIG_TABLE_NAME';
export const TENANT_PROVISION_WORKFLOW_FUNCTION_NAME_ENV_VAR = 'TENANT_PROVISION_WORKFLOW_FUNCTION_NAME';
export const TENANT_PROVISION_SYSTEM_USER_ID_ENV_VAR = 'TENANT_PROVISION_SYSTEM_USER_ID';
export const EVENT_BUS_NAME_ENV_VAR = 'EVENT_BUS_NAME';
export const PLATFORM_REST_API_ID_ENV_VAR = 'PLATFORM_REST_API_ID';
export const PLATFORM_REST_API_ROOT_RESOURCE_ID_ENV_VAR = 'PLATFORM_REST_API_ROOT_RESOURCE_ID';
export const DEFAULT_ORCHESTRATOR_MODEL_ID_ENV_VAR = 'DEFAULT_ORCHESTRATOR_MODEL_ID';

export const WORKFLOW_MAX_AGENTS = 10;

export const REQUIRED_ENV_VARS = [
    USE_CASES_TABLE_NAME_ENV_VAR,
    USE_CASE_CONFIG_TABLE_NAME_ENV_VAR,
    TENANT_PROVISION_WORKFLOW_FUNCTION_NAME_ENV_VAR,
    EVENT_BUS_NAME_ENV_VAR,
    PLATFORM_REST_API_ID_ENV_VAR
];
