// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const TENANTS_TABLE_NAME_ENV_VAR = 'TENANTS_TABLE_NAME';
export const USE_CASES_TABLE_NAME_ENV_VAR = 'USE_CASES_TABLE_NAME';
export const USE_CASE_CONFIG_TABLE_NAME_ENV_VAR = 'USE_CASE_CONFIG_TABLE_NAME';
export const TENANT_PROVISION_AGENT_FUNCTION_NAME_ENV_VAR = 'TENANT_PROVISION_AGENT_FUNCTION_NAME';
export const TENANT_PROVISION_MCP_FUNCTION_NAME_ENV_VAR = 'TENANT_PROVISION_MCP_FUNCTION_NAME';
export const TENANT_PROVISION_SYSTEM_USER_ID_ENV_VAR = 'TENANT_PROVISION_SYSTEM_USER_ID';
export const TOOL_CONNECTION_OAUTH_PROVIDERS_ENV_VAR = 'TOOL_CONNECTION_OAUTH_PROVIDERS_JSON';
export const EVENT_BUS_NAME_ENV_VAR = 'EVENT_BUS_NAME';
/** Deployment platform API Gateway REST API (required for MCP gateway CFN). */
export const PLATFORM_REST_API_ID_ENV_VAR = 'PLATFORM_REST_API_ID';
export const PLATFORM_REST_API_ROOT_RESOURCE_ID_ENV_VAR = 'PLATFORM_REST_API_ROOT_RESOURCE_ID';

export const REQUIRED_ENV_VARS = [
    TENANTS_TABLE_NAME_ENV_VAR,
    USE_CASES_TABLE_NAME_ENV_VAR,
    USE_CASE_CONFIG_TABLE_NAME_ENV_VAR,
    TENANT_PROVISION_AGENT_FUNCTION_NAME_ENV_VAR,
    TENANT_PROVISION_MCP_FUNCTION_NAME_ENV_VAR,
    EVENT_BUS_NAME_ENV_VAR,
    PLATFORM_REST_API_ID_ENV_VAR
];
