// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const TENANTS_TABLE_NAME_ENV_VAR = 'TENANTS_TABLE_NAME';
export const TENANT_PROVISION_AGENT_FUNCTION_NAME_ENV_VAR = 'TENANT_PROVISION_AGENT_FUNCTION_NAME';
export const TENANT_PROVISION_SYSTEM_USER_ID_ENV_VAR = 'TENANT_PROVISION_SYSTEM_USER_ID';

export const REQUIRED_ENV_VARS = [
    TENANTS_TABLE_NAME_ENV_VAR,
    TENANT_PROVISION_AGENT_FUNCTION_NAME_ENV_VAR
];
