// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const EVENT_BUS_NAME_ENV_VAR = 'EVENT_BUS_NAME';
export const TOOL_CONNECTION_OAUTH_PROVIDERS_ENV_VAR = 'TOOL_CONNECTION_OAUTH_PROVIDERS_JSON';
export const USE_CASES_TABLE_NAME_ENV_VAR = 'USE_CASES_TABLE_NAME';
export const USE_CASE_CONFIG_TABLE_NAME_ENV_VAR = 'USE_CASE_CONFIG_TABLE_NAME';

export const REQUIRED_ENV_VARS = [
    EVENT_BUS_NAME_ENV_VAR,
    TOOL_CONNECTION_OAUTH_PROVIDERS_ENV_VAR,
    USE_CASES_TABLE_NAME_ENV_VAR,
    USE_CASE_CONFIG_TABLE_NAME_ENV_VAR
];
