# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Shared AIW runtime environment variable names (no imports from other aiw_* modules)."""

AIW_TENANT_ENV = "AIW_TENANT_ID"
AIW_OAUTH_WORKLOAD_ENV = "AIW_OAUTH_WORKLOAD_NAME"
AIW_OAUTH_CALLBACK_ENV = "AIW_OAUTH_CALLBACK_URL"
AIW_POLICY_ALLOW_MERGE_ENV = "AIW_POLICY_ALLOW_MERGE"
AIW_POLICY_ALLOW_PULL_REQUEST_CREATE_ENV = "AIW_POLICY_ALLOW_PULL_REQUEST_CREATE"
AIW_POLICY_ALLOW_PULL_REQUEST_REVIEW_ENV = "AIW_POLICY_ALLOW_PULL_REQUEST_REVIEW"
